### ISSUE TITLE
[Feature] Support physical devices with -d option to start VM

### ISSUE THREAD

**Issue by bigfish24** [chef/anka-buildkite-plugin#20]
Anka supports running tests on physical devices. To do so, you must setup the device to be claimed and then start the VM with its name or ID such as:

```
anka start -d iOS12iPhone [VMName]
```

Currently the plugin does not invoke the start command and instead simply uses `anka run` which implicitly invokes `start`, preventing the use of the device option.

The plugin would instead need to call `start` with the device option if supplied before calling `run`. The user should be able to supply the device name(s) in the configuration (you can supply multiple devices if you need more than one, such as `-d 337641472 -d 339738624 -d 341835776`).

**Comment by NorseGaud** [comment]
Shouldn't be too hard of an improvement to add. Want to take a stab at it and do a PR?

**Comment by bigfish24** [comment]
Added via https://github.com/chef/anka-buildkite-plugin/pull/21
