### ISSUE TITLE
Overloaded hosts lead to race conditions in pipelines

### ISSUE THREAD

**Issue by tas50** [chef/anka-buildkite-plugin#23]
# Describe the problem
We have a single host in the cluster today and multiple jobs are failing with race conditions related the DMGs when verifying builds.

```
:anka: Cloning macos-omnibus-10.14 to macos-omnibus-10.14-e0fba51a-1f5c-41fa-b7b9-88b2b1aab0b8
Executing . ./.omnibus-buildkite-plugin/test-settings.sh && ./omnibus/omnibus-test.sh in macos-omnibus-10.14-e0fba51a-1f5c-41fa-b7b9-88b2b1aab0b8
Installing unstable chefdk 4.3.7
No receipt for 'com.getchef.pkg.chefdk' found at '/'.
-anka: unmount /private/var/tmp/ankafs.0: Resource busy
```

See https://buildkite.com/chef/chef-chef-dk-master-omnibus-release/builds/54#e0fba51a-1f5c-41fa-b7b9-88b2b1aab0b8

## Stacktrace

<details><summary>  </summary>
```
```
</details>

**Comment by tduffield** [comment]
We don't use this plugin for Omnibus builds. Please re-open against `chef/omnibus-buildkite-plugin` if this is still an issue.
